apiVersion: apps/v1
kind: Deployment
metadata:
  name: hieuweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hieuweb
  template:
    metadata:
      labels:
        app: hieuweb
    spec:
      containers:
      - name: hieuweb
        image: hoangcucu/hieujava:1.0
        ports:
        - containerPort: 8181